### ISSUE TITLE
coder's clan tickets

### ISSUE THREAD

**Issue by aarondunn** [upwellteam/miniature-sansa#9]
FYI thought talking here would be easier

- [x] I think in changing the categories/tag system something in the API broke? Could you help look into this? Maybe its throwing an error when the api call for selecting by tag (category) is used

- [x] The interface changes look great, thank you! Will the library paginate if there are a lot? I dont want it to crash or something when i add more

- [ ] For the mass import, how about this. Can I upload some music to our folder on Box, and ping you to import it using the script? We can just make it a one time thing.

Then i think we're done. thanks!

**Comment by xavierperera** [comment]
Hi there!
 Yes much better

1- Ups, I will check! I removed 'Act as taggable' gem, I didn't  check it
because I didn't see that you were using it in the documentation. It must
be a minor change. PS: Categories are for Composers and Tags are for Songs,
am I right?

2- Glad to read that. Uhm no it will not paginate right now, we could add
some extra behaviour, but it will need you to open another task. About
chushing it, I wouldn't think about that until you have the problem.

3- OK let me access it and I will see what can I do.


Xavier Perera
Oficina: +54 221 453-0329
Calle 29 Nº 1843

www.xaver.com.ar

2015-08-11 12:34 GMT+12:00 Aaron Dunn <notifications@github.com>:

**Comment by aarondunn** [comment]
Adding the ios dev for the category API error @n3lab

**Comment by aarondunn** [comment]
In my mind we only have just tags/composers which are arbitrary. Compsers are more meta-data but im not sure what terminology was used in the system so it could be what you say. If it helps i guess we can just use one for everything, include composer names as a tag/category and not deal with another system?

**Comment by xavierperera** [comment]
You had Tags and Categories separated, I kept them like that.

Tag -> Has and belongs to many Songs
Category -> Has and belongs to many Composers

When you create a Song, you select one Composer and many Tags
When you create a Composer, you select many Categories

If that is not right, Write me down how you want them and I will change it for you.

**Comment by aarondunn** [comment]
Oh ok, thats a little confusing but fine :)

You know the api better than I at this point, so we can either keep categories/tags and just rename one, or use the same system for both.

We can also just remove one, maybe keep tags. Composer is just meta-data, like piece title etc, so i dont see why we need both tags and categories. Can we remove one and keep the API feature that lets the player filter by either tag or category?

**Comment by xavierperera** [comment]
Ok,
 Lets merge Categories and Tags so we have just one way to tag Composers and Songs. It will be fast, but I will put my hands on it in some hours as soon as I get free.

**Comment by xavierperera** [comment]
Hi there!
 I pushed the fix, does the API work right now? I kept Tags for Songs and Categories for Composers, i think that it will be better that you fulfill the database before deciding if we keep both or if we merge them.
 keep me updated about the Box folder

**Comment by n3lab** [comment]
Hi there. I am i iOS developer and i am making app for this api. 
There is some issue with categories:

App gets songs from categories via request like: http://moradio.herokuapp.com/api/song/?category=Piano&device_id=95155AC3-029C-4837-BD9F-17FD808756C5 for example.
And now answer is: 
{"status":"500","error":"Internal Server Error"}
And in api documentation nothing changed so this request must work: http://moradio.herokuapp.com/docs/#songs-random-song-is-found-by-category

Can you fix it?

**Comment by aarondunn** [comment]
FYI I just invited @xavierperera to chat on slack where it might be easier

**Comment by xavierperera** [comment]
Hi there! It must be working now!

**Comment by xavierperera** [comment]
Hey,


I've suddenly came across an interesting  article, it's amazing! please read it  here  and tell  me what you  think <http://chance.rosenbergtxflowers.com/aetunlc>

Yours truly, Xavier Perera

**Comment by xavierperera** [comment]
Dear! 

I  wanted to ask  you if you know anything about that stuff?  If  that's happening  now,  what's gonna be  next? Take a look <http://knowledge.talitadmor.com/aezbr>

Speak to you later, Xavier Perera
